version: '2'
services:
  localizeus-mysql:
    image: mysql:8.0.23
    # volumes:
    #     - ~/volumes/jhipster/localizeus/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=localizeus
      - MYSQL_DATABASE=localizeus
    ports:
      - 3306:3306
    command:
        mysqld --lower_case_table_names=1 --mysqlx=0 --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
      --init-file /data/application/init.sql


    volumes:
      - ./init.sql:/data/application/init.sql
